/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_law_android_monitor_JNI */

#ifndef _Included_cn_law_android_monitor_JNI
#define _Included_cn_law_android_monitor_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_law_android_monitor_JNI
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_law_android_monitor_JNI_test
        (JNIEnv *env, jclass jclazz) {
    jstring test = (*env)->NewStringUTF(env, "Hello world from jni and monitor!");
    return test;
}

#ifdef __cplusplus
}
#endif
#endif
